version: '3.3'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: udemy2
        restart: always
        volumes:
            - ./dbdump:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        depends_on:
            - db
        env_file:
            - .env

    prestashop:
        depends_on:
            - db
        ports:
            - 80:80
            - 443:443
        image: karabiniewicz/be_172588
        # build: 
        #     context: .
        #     dockerfile: Dockerfile
        environment:
            ALLOW_OVERRIDE: 1
            PS_INSTALL_AUTO: 0
            PS_ERASE_DB: 0
            DB_SERVER: db
            DB_USER: root
            DB_PASSWD: root
            DB_NAME: udemy2
            PS_DEV_MODE: 0 # 0 by default 1 for volumes
            PS_DOMAIN: localhost:80
        restart: always
        volumes:
            - ./webshop:/var/www/html
            - ./ssl:/etc/apache2/sites-available
