version: '3.3'

services:
   druzynaA:
        ports:
            - 2588:80
            - 2589:443
        image: karabiniewicz/be_172588
        environment:
            ALLOW_OVERRIDE: 1
            PS_INSTALL_AUTO: 0
            PS_ERASE_DB: 0
            DB_USER: be_172588
            DB_PASSWD: root
            DB_NAME: be_172588
            DB_SERVER: actina15.maas
            PS_DEV_MODE: 0
            PS_DOMAIN: localhost:2588
            PS_DOMAIN_SSL: localhost:2589
        restart: always
        networks:
            - admin-mysql_default
networks:
    admin-mysql_default:
        external:
            name: admin-mysql_default